x,y,z=1,2,3;
simpleString="Spam";
L=[1,2,3,4];
dic={"a":1,"b":2,"c":3};
fileObject=open("Files\\Storage1.txt","r+");
fileObject.write(simpleString+"\n")
fileObject.write("%s,%s,%s\n"%(x,y,z));
fileObject.write(str(L)+"$"+str(dic)+"\n");
fileObject.flush();
print("Moving Pointer to the Start");
fileObject.seek(0);
fileData=fileObject.read();
print(fileData);
print("Again moving the pointer to the start of the file.");
fileObject.seek(0);
fLine=fileObject.readline();
print(repr(fLine));
fLine=fLine.rstrip();
print(fLine);
fLine2=fileObject.readline();
print(repr(fLine2));
fLine2=fLine2.split(',');
print(fLine2);
print([int(x) for x in fLine2 ]);
fLine3=fileObject.readline();
print(repr(fLine3));
fLine3=fLine3.split('$');
print(fLine3);
fLine3=[eval(part) for part in fLine3];
print(fLine3);
fileObject.close();